### ISSUE TITLE
Try to manually export EC2 instance on EC2

### ISSUE THREAD

**Issue by Dorajia** [Dorajia/CMPE283-Project#4]

**Comment by MiaoS** [comment]
S3 permission issues:
http://docs.aws.amazon.com/vm-import/latest/userguide/vmexport.html

added permission for vm-import-export@amazon.com still blocked from export ec2 instance

Error message:
Caught an AmazonServiceException, which means your request made it to Amazon EC2, but was rejected with an error response for some reason.
Error Message:    Could not read the ACL associated with the S3 bucket. (Service: AmazonEC2; Status Code: 400; Error Code: InvalidParameterValue; Request ID: 987ba5a5-b928-472f-9ca5-64ef39de08d5)
HTTP Status Code: 400
AWS Error Code:   InvalidParameterValue
Error Type:       Unknown
Request ID:       987ba5a5-b928-472f-9ca5-64ef39de08d5

**Comment by MiaoS** [comment]
cli command:
aws ec2 create-instance-export-task --instance-id i-12a8348c --target-environment vmware --export-to-s3-task DiskImageFormat=VMDK,ContainerFormat=ova,S3Bucket=cmpe283-test

java programme: google driver shared folder/playground/exportEc2.java

**Comment by Dorajia** [comment]
we can only export the EC2 that previously imported from VM virtualization before, this may be the problem.
