### ISSUE TITLE
Research on AWS Java API

### ISSUE THREAD

**Issue by Dorajia** [Dorajia/CMPE283-Project#5]
Research if AWS have api has api to export the ec2 instance.

**Comment by MiaoS** [comment]
https://aws.amazon.com/ec2/vm-import/
http://docs.aws.amazon.com/vm-import/latest/userguide/vmexport.html
http://docs.aws.amazon.com/amp/latest/userguide/migrate-vms.html#migrate-prerequisites
http://docs.aws.amazon.com/amp/latest/userguide/introduction.html
http://docs.aws.amazon.com/amp/latest/userguide/manage-instances.html

http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/ec2/model/ImportInstanceRequest.html
http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/ec2/AmazonEC2.html

**Comment by MiaoS** [comment]
http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/auth/profile/ProfileCredentialsProvider.html
